### ISSUE TITLE
Support uploading large media files

### ISSUE THREAD

**Issue by rhys-vdw** [ayrshare/social-post-api#1]
https://docs.ayrshare.com/rest-api/endpoints/media#upload-large-media-files

I need this feature. Do you accept PRs?

**Comment by gbourne1** [comment]
Yes, if you have an improvement on the Node.js package.

**Comment by rhys-vdw** [comment]
Ah, bit of a delay there. I ended up deciding to put Ayrshare to rest for a bit, might bring it back later.
