### ISSUE TITLE
supports 3 leg oauth ?

### ISSUE THREAD

**Issue by rowntreerob** [ayrshare/social-post-api#2]
noticed the plugin over on bubble while looking for wrappers for 3-legged-oauth scenario where any with media account hits the api landing page and ANY USER resolves steps for auth / access tokens so that THEIR respective SM accounts are used ...

They access the app i develop ONLY as a wrapper to 3rd party SM accounts in their name.

Twitter terms of service would be violated if i wrote an app that fronted them and posted on behalf of multiple users on twitter using only a single account. 

Let me know if im mistaken  and your service accommodate oauth and post to twitter using that users account ( or any users that hits my api ) 

thx .

If i scan ur docs and see zero hits on oauth, i know i have a problem and feature gap regarding whats described above.

**Comment by gbourne1** [comment]
When you or your user authorizes access to post/analytics on their social account, the OAuth (3-legged) is used to permissions access. Ayrshare handles all of this for you, but you can view the process of each social network. For example Facebook: https://developers.facebook.com/docs/facebook-login/guides/access-tokens
